name:         bitwise-enum
version:      1.0.1.1
github:       "jnbooth/bitwise-enum"
homepage:     https://github.com/jnbooth/bitwise-enum
bug-reports:  https://github.com/jnbooth/bitwise-enum/issues
author:       "Joshua Booth <joshua.n.booth@gmail.com>"
maintainer:   "Joshua Booth <joshua.n.booth@gmail.com>"
license:      BSD3
license-file: LICENSE
category:     Data, Data Structures, Foreign
synopsis:     "Bitwise operations on bounded enumerations"
description:  |
    Bitwise operations on bounded enumerations.
    .
    ["Data.Enum.Set"] Constant-time sets using bit flags.
    .
    ["Data.Enum.Memo"] Constant-time lookup memoization for functions on enumerated types.

tested-with: |
  GHC ==8.6.1
   || ==8.6.5
   || ==8.8.4
   || ==8.10.7
   || ==9.0.2
   || ==9.2.8
   || ==9.4.5
   || ==9.6.2

dependencies:
  - aeson >=0.11 && <2.3
  - array >=0.5.1 && <0.6
  - base >=4.12 && <5
  - deepseq >=1.1 && <1.6
  - mono-traversable >=1.0.12 && <1.1
  - vector >=0.11 && <0.14

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -ferror-spans
  - -funbox-small-strict-fields

library:
  source-dirs: ./
  ghc-options: -O2

benchmarks:
  enumset-benchmarks:
    main: EnumSet.hs
    source-dirs: benchmarks
    dependencies:
      - base
      - bitwise-enum
      - gauge >=0.2.5
      - wide-word >=0.1.0.9
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
      - -O2

tests:
  enumset-test-suite:
    main: set-properties.hs
    source-dirs: tests
    dependencies:
      - base
      - bitwise-enum
      - QuickCheck >=2.13.2
      - test-framework >=0.8.2.0
      - test-framework-quickcheck2 >=0.3.0.5
